version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: moneyflow-db
    environment:
      POSTGRES_DB: moneyflow_dev
      POSTGRES_USER: moneyflow
      POSTGRES_PASSWORD: moneyflow123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - moneyflow-network

  redis:
    image: redis:7-alpine
    container_name: moneyflow-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - moneyflow-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: moneyflow-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@moneyflow.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    networks:
      - moneyflow-network

volumes:
  postgres_data:
  redis_data:

networks:
  moneyflow-network:
    driver: bridge